### ISSUE TITLE
setting the socket.io path

### ISSUE THREAD

**Issue by waldenn** [souramoo/party#3]
Hi,

What an interesting spatial videochat app, very cool idea!

I have tried to install the app (as an experiment) on my own project server at: https://conze.pt/app/chat

I had to change the base URL on some lines in "src/client/assets.js", "src/client/html/index.html" and "src/client/html/join.html". It would be nice to have some global-setting for this I think.

Two issues I have currently:

1) The [welcome screen](https://conze.pt/app/chat) text is shifted to the left-side (in Firefox and Chrome). I have made no CSS changes. Not sure whats causing this.

2) When clicking "[join](https://conze.pt/app/chat/join)" link, I get a 404 error code for accessing "https://conze.pt/socket.io/?EIO=3&transport=polling&t=N5mswUD" (instead of "https://conze.pt/app/chat/socket.io/?EIO=3&transport=polling&t=N5mswUD"). Any idea where/how I can get the base URL changed for socket.io?  I tried adding a resource "/app/chat" to the socket setup in networking.js, but that did not fix this. I am not yet too familiar with socket.io programming :-)

Thanks!

**Comment by souramoo** [comment]
Hi,

Thanks for trying it out!

1. I got a 503 error so can't comment on that I'm afraid! I suspect it's because the css files aren't loaded?

2. From https://stackoverflow.com/questions/12824612/change-socket-io-static-file-serving-path
"For socket.io version 1.2.1, this works for me.

Server side:

`var io = require('socket.io')({path: '/foo/bar'});`
Client side:

`var socket = io.connect('http://example.com', {path: '/foo/bar'});`
FYI: http://socket.io/docs/migrating-from-0-9/#configuration-differences
"
:)

**Comment by waldenn** [comment]
Hey, thanks. Got it working with your tips. Looking forward to learning a bit more about the code structure and I hope you keep improving this app, as I think the idea is great.

When I get to it, I want to try and integrate your party app into my conze.pt project, so people can chat about any topic on Wikipedia.

PS: Mobile seems to be a bit flaky (on my Firefox and Chrome browser with Android 9), as it disconnects quickly after making a connection.
